### ISSUE TITLE
Data manipulation framework

### ISSUE THREAD

**Issue by iamfullofspam** [e-gillies-ix/track-finding-yandex#1]
First we need to have ability to access data from IPython in convenient way (this should be organized as `data.py`)

The proposed interface is (this is draft):
* all the wires of detector are enumerated 
* `get_wires_deposited_energies(event)` return numpy.array of shape [n_wires]
* `get_wires_labels(event)` returns ground truth labels for each wire (like 0 - nothing, 1 - signal track, 2 - DOI track, 3 - other bck track, 4 - complex situation),  numpy.array of shape [n_wires]
* <strike> `get_tracks(event)` returns a list of tracks in this event, each track is described by r - radius,  and positions of it's center (rho_center, phi_center) </strike>
* `get_wires_layers()` returns numpy.array of shape [n_wires], number of layer from 1 to 20
* `get_wires_types()` returns numpy.array of shape [n_wires], type of each wire (0=G, 1=F, 2=S, ...)
* `get_wires_phis()` - phi for each wire
* `get_wires_rhos()` - rho for each wire
* `get_stereo_angle()` - they should be constant across the layer
* `get_neighbors()` - `scipy.sparse` matrix of shape [n_wires,  n_wires], with ones in the positions of neighbors (neighbors = 3 closest in the outer layer, 3 closest in the inner layer, 2 from the same layer, but this is to be discussed - we need same meaning of this for all nodes of same type, this isn't simple)

For Hough transform (no conformal mapping meanwhile):
* We have the set of possible tracks, each described by rho and phi (since radius is constant), these two variables are discretized and we enumerate possible positions (bins) of center. 
* `get_track_phis()` - returns numpy.array of shape [n_track_bins], each contains the phis of track's centers
* `get_track_rhos()` - rho's are in range [r - r_target, r + r_target]
* `get_wire_track_correspondence()` - return scipy.sparse matrix of shape [n_wires, n_track_bins], where we have 'probability' of a particular wire to be activated by some track with center inside the bin.

Provided this, plotting/training should be quite straghtforward.

<strike>In perspective:
* measure_quality(prediction, event) - if we provide a set of tracks (rho, phi, radius), predict which of them are wrong (duplicates problem here)
* measure_overall_quality(predictions, events) - final metric to be optimized
<\strike>

We don't need those functions, wire-wise comparison of quality is possible.

**Comment by e-gillies-ix** [comment]
https://www.dropbox.com/s/n8mgqh6yzp6j1sd/signal.140905M02.noise.root?dl=0

**Comment by iamfullofspam** [comment]
Made some changes to interface (deleted three methods)
